# Generated by Django 6.0.5 on 2026-05-18 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('estadio', models.CharField(default='Estadio Principal', max_length=100, verbose_name='Estadio/Cancha')),
                ('goles_local', models.IntegerField(default=0, verbose_name='Goles Local')),
                ('goles_visitante', models.IntegerField(default=0, verbose_name='Goles Visitante')),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso / Match Day'), ('finalizado', 'Finalizado')], default='programado', max_length=20, verbose_name='Estado del Partido')),
                ('jornada', models.IntegerField(default=1, verbose_name='Jornada/Fecha')),
                ('temporada', models.CharField(default='Temporada Apertura 2026', max_length=50, verbose_name='Temporada')),
                ('firma_vocal', models.BooleanField(default=False, verbose_name='Firma del Vocal')),
                ('firma_capitan_local', models.BooleanField(default=False, verbose_name='Firma Capitán Local')),
                ('firma_capitan_visitante', models.BooleanField(default=False, verbose_name='Firma Capitán Visitante')),
                ('arbitro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_arbitrados', to=settings.AUTH_USER_MODEL, verbose_name='Árbitro Principal')),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='teams.equipo', verbose_name='Equipo Local')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='teams.equipo', verbose_name='Equipo Visitante')),
                ('vocal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_vocalizados', to=settings.AUTH_USER_MODEL, verbose_name='Vocal de Campo')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
            },
        ),
        migrations.CreateModel(
            name='EventoPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gol', 'Gol'), ('amarilla', 'Tarjeta Amarilla'), ('roja', 'Tarjeta Roja'), ('cambio', 'Cambio de Jugador')], max_length=20, verbose_name='Tipo de Evento')),
                ('minuto', models.IntegerField(verbose_name='Minuto')),
                ('detalle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Detalles adicionales')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.equipo', verbose_name='Equipo del Evento')),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_partido', to=settings.AUTH_USER_MODEL, verbose_name='Jugador Involucrado')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='matches.partido')),
            ],
            options={
                'verbose_name': 'Evento de Partido',
                'verbose_name_plural': 'Eventos de Partidos',
            },
        ),
    ]
