# Generated by Django 6.0.5 on 2026-05-19 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('teams', '0002_equipo_entrenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='fase',
            field=models.CharField(choices=[('regular', 'Liga / Fecha Regular'), ('grupos', 'Fase de Grupos'), ('octavos', 'Octavos de Final'), ('cuartos', 'Cuartos de Final'), ('semifinal', 'Semifinales'), ('final', 'Final')], default='regular', max_length=20, verbose_name='Fase del Torneo'),
        ),
        migrations.AddField(
            model_name='partido',
            name='firma_arbitro_img',
            field=models.TextField(blank=True, null=True, verbose_name='Firma Digital Árbitro (PNG Base64)'),
        ),
        migrations.AddField(
            model_name='partido',
            name='firma_entrenador_local_img',
            field=models.TextField(blank=True, null=True, verbose_name='Firma Entrenador Local (PNG Base64)'),
        ),
        migrations.AddField(
            model_name='partido',
            name='firma_entrenador_visitante_img',
            field=models.TextField(blank=True, null=True, verbose_name='Firma Entrenador Visitante (PNG Base64)'),
        ),
        migrations.AddField(
            model_name='partido',
            name='firma_vocal_img',
            field=models.TextField(blank=True, null=True, verbose_name='Firma Digital Vocal (PNG Base64)'),
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Torneo / Liga')),
                ('tipo', models.CharField(choices=[('liga', 'Liga (Todos contra todos por fechas)'), ('torneo', 'Torneo (Fase de Grupos + Eliminatorias)')], default='liga', max_length=20, verbose_name='Tipo de Campeonato')),
                ('temporada', models.CharField(default='Temporada 2026', max_length=50, verbose_name='Temporada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('equipos', models.ManyToManyField(related_name='torneos', to='teams.equipo', verbose_name='Equipos Participantes')),
            ],
            options={
                'verbose_name': 'Torneo / Liga',
                'verbose_name_plural': 'Torneos y Ligas',
            },
        ),
        migrations.AddField(
            model_name='partido',
            name='torneo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='matches.torneo', verbose_name='Torneo / Competencia'),
        ),
    ]
