# Generated by Django 6.0.4 on 2026-05-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_partido_fase_partido_firma_arbitro_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='grupo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Grupo (Fase de Grupos)'),
        ),
    ]
