# Generated by Django 6.0.4 on 2026-06-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_partido_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='alineacion_local',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Alineación Local del Partido'),
        ),
        migrations.AddField(
            model_name='partido',
            name='alineacion_visitante',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Alineación Visitante del Partido'),
        ),
    ]
