# Generated by Django 4.2.30 on 2026-08-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_partido_alineacion_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='categoria',
            field=models.CharField(choices=[('senior', 'Senior / Libre'), ('master', 'Máster (Mayores de 40)'), ('supermaster', 'Supermáster (Mayores de 50)'), ('juvenil', 'Juvenil (Sub-18)'), ('u15', 'Sub-15 (U-15)'), ('u12', 'Sub-12 (U-12)'), ('femenino', 'Femenino Libre')], default='senior', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='eventopartido',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
