# Generated by Django 4.2.30 on 2026-08-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_torneo_categoria_alter_eventopartido_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='max_jugadores_por_equipo',
            field=models.IntegerField(default=25, verbose_name='Máximo de Jugadores por Equipo'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='modalidad',
            field=models.CharField(default='Fútbol 11', max_length=50, verbose_name='Modalidad (ej. Fútbol 11, Fútbol 7)'),
        ),
    ]
