# Generated by Django 4.2.30 on 2026-08-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_torneo_max_jugadores_por_equipo_torneo_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventopartido',
            name='tipo',
            field=models.CharField(choices=[('gol', 'Gol'), ('asistencia', 'Asistencia'), ('amarilla', 'Tarjeta Amarilla'), ('roja', 'Tarjeta Roja'), ('cambio', 'Cambio de Jugador')], max_length=20, verbose_name='Tipo de Evento'),
        ),
    ]
