# Generated by Django 4.2.30 on 2026-08-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_alter_eventopartido_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='costo_amarilla',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Costo de Tarjeta Amarilla (C$)'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='costo_roja',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10, verbose_name='Costo de Tarjeta Roja (C$)'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='limite_amarillas_suspension',
            field=models.IntegerField(default=3, verbose_name='Límite Amarillas para Suspensión'),
        ),
    ]
