# Generated by Django 4.2.30 on 2026-08-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_torneo_costo_amarilla_torneo_costo_roja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='costo_amarilla',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='Costo de Tarjeta Amarilla ($)'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='costo_roja',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10, verbose_name='Costo de Tarjeta Roja ($)'),
        ),
    ]
