# Generated by Django 4.2.30 on 2026-08-17 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_categoria_alter_equipo_categoria_equipo_categoria_fk'),
        ('matches', '0009_alter_torneo_costo_amarilla_alter_torneo_costo_roja'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='categoria_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teams.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='categoria',
            field=models.CharField(choices=[('senior', 'Senior / Libre'), ('master', 'Máster (Mayores de 40)'), ('supermaster', 'Supermáster (Mayores de 50)'), ('juvenil', 'Juvenil (Sub-18)'), ('u15', 'Sub-15 (U-15)'), ('u12', 'Sub-12 (U-12)'), ('femenino', 'Femenino Libre')], default='senior', max_length=20, verbose_name='Categoría (Original)'),
        ),
    ]
