# Generated by Django 4.2.30 on 2026-08-17 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_remove_equipo_categoria_fk_alter_equipo_categoria'),
        ('matches', '0010_torneo_categoria_fk_alter_torneo_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='categoria',
        ),
        migrations.RenameField(
            model_name='torneo',
            old_name='categoria_fk',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='torneo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.categoria', verbose_name='Categoría'),
        ),
    ]
