# Generated by Django 4.2.30 on 2026-09-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_organizacion_usuarioorganizacion'),
        ('matches', '0011_remove_torneo_categoria_fk_alter_torneo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización'),
        ),
    ]
