# Generated by Django 4.2.30 on 2026-09-03 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_data_migration_org'),
        ('matches', '0012_partido_organizacion_torneo_organizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='organizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='torneo',
            name='organizacion',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización'),
            preserve_default=False,
        ),
    ]
