# Generated by Django 4.2.30 on 2026-09-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_role_alter_usuarioorganizacion_rol'),
        ('matches', '0013_alter_partido_organizacion_alter_torneo_organizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Torneo / Liga'),
        ),
        migrations.AlterUniqueTogether(
            name='torneo',
            unique_together={('organizacion', 'nombre')},
        ),
    ]
