# Generated by Django 4.2.30 on 2026-09-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_alter_torneo_nombre_alter_torneo_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='clasificados_por_grupo',
            field=models.IntegerField(default=2, verbose_name='Clasificados por Grupo'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='distribucion_grupos',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Distribución de Equipos en Grupos'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='fase_eliminatoria_inicial',
            field=models.CharField(choices=[('dieciseisavos', '16vos de Final'), ('octavos', 'Octavos de Final'), ('cuartos', 'Cuartos de Final'), ('semifinal', 'Semifinales')], default='octavos', max_length=20, verbose_name='Fase Eliminatoria Inicial'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='numero_grupos',
            field=models.IntegerField(default=2, verbose_name='Número de Grupos'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='fase',
            field=models.CharField(choices=[('regular', 'Liga / Fecha Regular'), ('grupos', 'Fase de Grupos'), ('dieciseisavos', '16vos de Final'), ('octavos', 'Octavos de Final'), ('cuartos', 'Cuartos de Final'), ('semifinal', 'Semifinales'), ('final', 'Final')], default='regular', max_length=20, verbose_name='Fase del Torneo'),
        ),
    ]
