# Generated by Django 4.2.30 on 2026-09-22 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0019_alter_equipo_unique_together_equipo_categorias_and_more'),
        ('matches', '0015_torneo_clasificados_por_grupo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='tipo',
            field=models.CharField(choices=[('liga', 'Liga (Todos contra todos por fechas)'), ('torneo', 'Torneo (Fase de Grupos + Eliminatorias)'), ('personalizado', 'Torneo Personalizado por Grupos (Sectores)')], default='liga', max_length=20, verbose_name='Tipo de Campeonato'),
        ),
        migrations.CreateModel(
            name='GrupoTorneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Grupo')),
                ('sector', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sector / Descripción')),
                ('orden', models.IntegerField(default=1, verbose_name='Orden de Presentación')),
                ('cupos_clasificacion', models.IntegerField(default=4, verbose_name='Cupos de Clasificación')),
                ('formato_enfrentamientos', models.CharField(choices=[('una_vuelta', 'Una Vuelta (Solo Ida)'), ('ida_vuelta', 'Ida y Vuelta')], default='una_vuelta', max_length=20, verbose_name='Formato de Enfrentamientos')),
                ('activo', models.BooleanField(default=True, verbose_name='Grupo Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_personalizados', to='matches.torneo', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Grupo de Torneo Personalizado',
                'verbose_name_plural': 'Grupos de Torneo Personalizado',
                'ordering': ['orden', 'id'],
                'unique_together': {('torneo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='EquipoGrupoTorneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden / Posición de Sorteo')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_torneo_personalizado', to='teams.equipo', verbose_name='Equipo')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_asignados', to='matches.grupotorneo', verbose_name='Grupo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_grupos_personalizados', to='matches.torneo', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Asignación de Equipo a Grupo',
                'verbose_name_plural': 'Asignaciones de Equipos a Grupos',
                'ordering': ['orden', 'id'],
                'unique_together': {('torneo', 'equipo'), ('grupo', 'equipo')},
            },
        ),
    ]
