# Generated by Django 4.2.30 on 2026-09-22 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_alter_customuser_role_alter_usuarioorganizacion_rol'),
        ('matches', '0016_alter_torneo_tipo_grupotorneo_equipogrupotorneo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='grupo_personalizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partidos', to='matches.grupotorneo', verbose_name='Grupo Personalizado'),
        ),
        migrations.AddField(
            model_name='partido',
            name='numero_vuelta',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Primera Vuelta'), (2, 'Segunda Vuelta')], default=1, verbose_name='Número de Vuelta'),
        ),
        migrations.CreateModel(
            name='BitacoraTorneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100, verbose_name='Acción Realizada')),
                ('detalles', models.TextField(blank=True, null=True, verbose_name='Detalles / Motivo')),
                ('valores_anteriores', models.JSONField(blank=True, default=dict, null=True, verbose_name='Valores Anteriores')),
                ('valores_nuevos', models.JSONField(blank=True, default=dict, null=True, verbose_name='Valores Nuevos')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora_logs', to='matches.torneo', verbose_name='Torneo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Bitácora de Torneo',
                'verbose_name_plural': 'Bitácoras de Torneos',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
