# Generated by Django 4.2.30 on 2026-09-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_partido_grupo_personalizado_partido_numero_vuelta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='puntos_derrota',
            field=models.IntegerField(default=0, verbose_name='Puntos por Derrota'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='puntos_empate',
            field=models.IntegerField(default=1, verbose_name='Puntos por Empate'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='puntos_victoria',
            field=models.IntegerField(default=3, verbose_name='Puntos por Victoria'),
        ),
    ]
