# Generated by Django 4.2.30 on 2026-09-22 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0019_alter_equipo_unique_together_equipo_categorias_and_more'),
        ('users', '0010_alter_customuser_role_alter_usuarioorganizacion_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0018_torneo_puntos_derrota_torneo_puntos_empate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificadoTorneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion_grupo', models.IntegerField(verbose_name='Posición en el Grupo')),
                ('puntos', models.IntegerField(default=0, verbose_name='Puntos Obtenidos')),
                ('diferencia_goles', models.IntegerField(default=0, verbose_name='Diferencia de Goles')),
                ('goles_favor', models.IntegerField(default=0, verbose_name='Goles a Favor')),
                ('bombo', models.IntegerField(default=1, verbose_name='Número de Bombo')),
                ('metodo_clasificacion', models.CharField(choices=[('posicion', 'Posición Directa'), ('tabla', 'Tabla de Posiciones'), ('empate_resuelto', 'Resolución de Empate'), ('decision_admin', 'Decisión Administrativa')], default='posicion', max_length=50, verbose_name='Método de Clasificación')),
                ('fecha_confirmacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Confirmación')),
                ('datos_tabla', models.JSONField(blank=True, default=dict, null=True, verbose_name='Fotografía de Estadísticas (JSON)')),
                ('activo', models.BooleanField(default=True, verbose_name='Clasificación Activa')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Confirmado Por')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones_torneo', to='teams.equipo', verbose_name='Equipo Clasificado')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificados_definitivos', to='matches.grupotorneo', verbose_name='Grupo de Origen')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificados_definitivos', to='matches.torneo', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Clasificado Definitivo de Torneo',
                'verbose_name_plural': 'Clasificados Definitivos de Torneos',
                'ordering': ['bombo', 'posicion_grupo', 'grupo', 'id'],
                'unique_together': {('torneo', 'equipo')},
            },
        ),
        migrations.CreateModel(
            name='ResolucionEmpateTorneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_resolucion', models.CharField(choices=[('partido_desempate', 'Partido de Desempate'), ('sorteo_admin', 'Sorteo Administrativo'), ('comision', 'Resolución de Comisión'), ('reglamento', 'Criterio Reglamentario Adicional'), ('otro', 'Otro Motivo')], default='sorteo_admin', max_length=50, verbose_name='Motivo / Criterio Utilizado')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación / Acta Administrativa')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Resolución')),
                ('equipo_ganador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empates_ganados', to='teams.equipo', verbose_name='Equipo Favorecido / Ganador')),
                ('equipos_empatados', models.ManyToManyField(related_name='empates_resueltos', to='teams.equipo', verbose_name='Equipos Involucrados')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones_empate', to='matches.grupotorneo', verbose_name='Grupo')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Resuelto Por')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resoluciones_empate', to='matches.torneo', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Resolución de Empate de Torneo',
                'verbose_name_plural': 'Resoluciones de Empates de Torneo',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='LlaveEliminatoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('regular', 'Liga / Fecha Regular'), ('grupos', 'Fase de Grupos'), ('dieciseisavos', '16vos de Final'), ('octavos', 'Octavos de Final'), ('cuartos', 'Cuartos de Final'), ('semifinal', 'Semifinales'), ('final', 'Final')], default='octavos', max_length=20, verbose_name='Fase Eliminatoria')),
                ('numero_llave', models.IntegerField(default=1, verbose_name='Número de Llave')),
                ('formato', models.CharField(choices=[('partido_unico', 'Partido Único'), ('ida_vuelta', 'Ida y Vuelta')], default='partido_unico', max_length=20, verbose_name='Formato de la Llave')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('programada', 'Programada'), ('en_curso', 'En Curso'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20, verbose_name='Estado de la Llave')),
                ('orden_visual', models.IntegerField(default=1, verbose_name='Orden de Presentación Visual')),
                ('es_bye', models.BooleanField(default=False, verbose_name='Es Pase Directo / BYE')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('clasificado_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llaves_clasificado_local', to='matches.clasificadotorneo', verbose_name='Clasificado Local')),
                ('clasificado_visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llaves_clasificado_visitante', to='matches.clasificadotorneo', verbose_name='Clasificado Visitante')),
                ('equipo_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llaves_local', to='teams.equipo', verbose_name='Equipo Local / Sembrado 1')),
                ('equipo_visitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llaves_visitante', to='teams.equipo', verbose_name='Equipo Visitante / Sembrado 2')),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llaves_ganadas', to='teams.equipo', verbose_name='Ganador de la Llave')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización')),
                ('siguiente_llave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llaves_previas', to='matches.llaveeliminatoria', verbose_name='Siguiente Llave (Ronda Posterior)')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llaves_eliminatorias', to='matches.torneo', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Llave Eliminatoria',
                'verbose_name_plural': 'Llaves Eliminatorias',
                'ordering': ['fase', 'numero_llave', 'id'],
                'unique_together': {('torneo', 'fase', 'numero_llave')},
            },
        ),
    ]
