# Generated by Django 4.2.30 on 2026-09-22 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_alter_customuser_role_alter_usuarioorganizacion_rol'),
        ('teams', '0019_alter_equipo_unique_together_equipo_categorias_and_more'),
        ('matches', '0019_clasificadotorneo_resolucionempatetorneo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='llaveeliminatoria',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Confirmado Por'),
        ),
        migrations.AddField(
            model_name='llaveeliminatoria',
            name='definido_por_penales',
            field=models.BooleanField(default=False, verbose_name='Definido por Penales'),
        ),
        migrations.AddField(
            model_name='llaveeliminatoria',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación'),
        ),
        migrations.AddField(
            model_name='llaveeliminatoria',
            name='goles_prorroga_local',
            field=models.IntegerField(default=0, verbose_name='Goles Prórroga Local'),
        ),
        migrations.AddField(
            model_name='llaveeliminatoria',
            name='goles_prorroga_visitante',
            field=models.IntegerField(default=0, verbose_name='Goles Prórroga Visitante'),
        ),
        migrations.AddField(
            model_name='llaveeliminatoria',
            name='goles_visitante_local',
            field=models.IntegerField(default=0, verbose_name='Goles de Visitante del Equipo Local'),
        ),
        migrations.AddField(
            model_name='llaveeliminatoria',
            name='goles_visitante_visitante',
            field=models.IntegerField(default=0, verbose_name='Goles de Visitante del Equipo Visitante'),
        ),
        migrations.AddField(
            model_name='llaveeliminatoria',
            name='hubo_prorroga',
            field=models.BooleanField(default=False, verbose_name='Hubo Prórroga'),
        ),
        migrations.AddField(
            model_name='llaveeliminatoria',
            name='marcador_global_local',
            field=models.IntegerField(default=0, verbose_name='Marcador Global Local'),
        ),
        migrations.AddField(
            model_name='llaveeliminatoria',
            name='marcador_global_visitante',
            field=models.IntegerField(default=0, verbose_name='Marcador Global Visitante'),
        ),
        migrations.AddField(
            model_name='llaveeliminatoria',
            name='metodo_definicion',
            field=models.CharField(blank=True, choices=[('marcador', 'Marcador Directo'), ('marcador_global', 'Marcador Global'), ('gol_visitante', 'Gol de Visitante'), ('prorroga', 'Prórroga'), ('penales', 'Penales'), ('bye', 'Pase Directo (BYE)'), ('decision_administrativa', 'Decisión Administrativa')], max_length=30, null=True, verbose_name='Método de Definición'),
        ),
        migrations.AddField(
            model_name='llaveeliminatoria',
            name='penales_local',
            field=models.IntegerField(blank=True, null=True, verbose_name='Penales Local'),
        ),
        migrations.AddField(
            model_name='llaveeliminatoria',
            name='penales_visitante',
            field=models.IntegerField(blank=True, null=True, verbose_name='Penales Visitante'),
        ),
        migrations.AddField(
            model_name='llaveeliminatoria',
            name='posicion_siguiente_llave',
            field=models.CharField(choices=[('local', 'Local'), ('visitante', 'Visitante')], default='local', max_length=10, verbose_name='Posición en Siguiente Llave'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='disputar_tercer_lugar',
            field=models.BooleanField(default=True, verbose_name='Disputar Partido por el Tercer Lugar'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='usar_gol_visitante',
            field=models.BooleanField(default=False, verbose_name='Usar Regla de Gol de Visitante'),
        ),
        migrations.AlterField(
            model_name='llaveeliminatoria',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('programada', 'Programada'), ('en_curso', 'En Curso'), ('lista_para_confirmar', 'Lista para Confirmar'), ('finalizada', 'Finalizada'), ('anulada', 'Anulada')], default='pendiente', max_length=20, verbose_name='Estado de la Llave'),
        ),
        migrations.AlterField(
            model_name='llaveeliminatoria',
            name='fase',
            field=models.CharField(choices=[('regular', 'Liga / Fecha Regular'), ('grupos', 'Fase de Grupos'), ('dieciseisavos', '16vos de Final'), ('octavos', 'Octavos de Final'), ('cuartos', 'Cuartos de Final'), ('semifinal', 'Semifinales'), ('tercer_lugar', 'Tercer Lugar'), ('final', 'Final')], default='octavos', max_length=20, verbose_name='Fase Eliminatoria'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='fase',
            field=models.CharField(choices=[('regular', 'Liga / Fecha Regular'), ('grupos', 'Fase de Grupos'), ('dieciseisavos', '16vos de Final'), ('octavos', 'Octavos de Final'), ('cuartos', 'Cuartos de Final'), ('semifinal', 'Semifinales'), ('tercer_lugar', 'Tercer Lugar'), ('final', 'Final')], default='regular', max_length=20, verbose_name='Fase del Torneo'),
        ),
        migrations.CreateModel(
            name='ResultadoFinalTorneo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_confirmacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Confirmación')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones / Acta de Premiación')),
                ('campeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campeonatos_ganados', to='teams.equipo', verbose_name='Campeón')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Confirmado Por')),
                ('cuarto_lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuartos_lugares', to='teams.equipo', verbose_name='Cuarto Lugar')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización')),
                ('subcampeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcampeonatos', to='teams.equipo', verbose_name='Subcampeón')),
                ('tercer_lugar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terceros_lugares', to='teams.equipo', verbose_name='Tercer Lugar')),
                ('torneo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_final', to='matches.torneo', verbose_name='Torneo')),
            ],
            options={
                'verbose_name': 'Resultado Final y Cuadro de Honor',
                'verbose_name_plural': 'Resultados Finales y Cuadros de Honor',
            },
        ),
    ]
