# Generated by Django 4.2.30 on 2026-09-22 21:06

from django.db import migrations, models
import uuid


def add_fields_and_generate_uuids(apps, schema_editor):
    Torneo = apps.get_model('matches', 'Torneo')
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        table_description = connection.introspection.get_table_description(cursor, Torneo._meta.db_table)
        existing_columns = [col.name for col in table_description]

        if 'es_publico' not in existing_columns:
            field = models.BooleanField(default=True, verbose_name='Torneo Publicado / Vista Pública Activa')
            field.set_attributes_from_name('es_publico')
            schema_editor.add_field(Torneo, field)

        if 'public_uuid' not in existing_columns:
            field = models.UUIDField(default=None, null=True, editable=False, verbose_name='Identificador Público UUID')
            field.set_attributes_from_name('public_uuid')
            schema_editor.add_field(Torneo, field)

        cursor.execute(f"SELECT id FROM {Torneo._meta.db_table}")
        torneo_ids = [row[0] for row in cursor.fetchall()]

        for tid in torneo_ids:
            cursor.execute(
                f"UPDATE {Torneo._meta.db_table} SET public_uuid = %s WHERE id = %s",
                [str(uuid.uuid4()), tid]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0020_llaveeliminatoria_confirmado_por_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_fields_and_generate_uuids, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='torneo',
                    name='es_publico',
                    field=models.BooleanField(default=True, verbose_name='Torneo Publicado / Vista Pública Activa'),
                ),
                migrations.AddField(
                    model_name='torneo',
                    name='public_uuid',
                    field=models.UUIDField(default=None, null=True, editable=False, verbose_name='Identificador Público UUID'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='torneo',
            name='public_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador Público UUID'),
        ),
    ]
