# Generated by Django 4.2.30 on 2026-09-22 21:06

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    Torneo = apps.get_model('matches', 'Torneo')
    for torneo in Torneo.objects.all():
        if not torneo.public_uuid:
            torneo.public_uuid = uuid.uuid4()
            torneo.save(update_fields=['public_uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0020_llaveeliminatoria_confirmado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='es_publico',
            field=models.BooleanField(default=True, verbose_name='Torneo Publicado / Vista Pública Activa'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='public_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, verbose_name='Identificador Público UUID'),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='torneo',
            name='public_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador Público UUID'),
        ),
    ]
