# Generated by Django 4.2.30 on 2026-09-27 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_role_alter_usuarioorganizacion_rol'),
        ('matches', '0021_torneo_es_publico_torneo_public_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Estadio / Cancha')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección / Ubicación')),
                ('ciudad', models.CharField(blank=True, default='Ambato', max_length=100, null=True, verbose_name='Ciudad')),
                ('capacidad', models.IntegerField(blank=True, null=True, verbose_name='Capacidad')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadios', to='users.organizacion', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Estadio / Cancha',
                'verbose_name_plural': 'Estadios y Canchas',
                'ordering': ['nombre'],
                'unique_together': {('organizacion', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='partido',
            name='estadio_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos', to='matches.estadio', verbose_name='Estadio Registrado'),
        ),
    ]
