# Generated by Django 6.0.5 on 2026-05-18 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Equipo')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_equipos/', verbose_name='Escudo/Logo')),
                ('categoria', models.CharField(choices=[('senior', 'Senior / Libre'), ('master', 'Máster (Mayores de 40)'), ('supermaster', 'Supermáster (Mayores de 50)'), ('juvenil', 'Juvenil (Sub-18)'), ('femenino', 'Femenino Libre')], default='senior', max_length=20, verbose_name='Categoría')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('dirigente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_dirigidos', to=settings.AUTH_USER_MODEL, verbose_name='Dirigente / Representante')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='FichaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='jugadores/selfies/', verbose_name='Foto / Selfie Carnet')),
                ('cedula_frontal', models.ImageField(blank=True, null=True, upload_to='jugadores/cedulas/', verbose_name='Cédula Frontal')),
                ('cedula_posterior', models.ImageField(blank=True, null=True, upload_to='jugadores/cedulas/', verbose_name='Cédula Posterior')),
                ('estado_validacion', models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('aprobado', 'Aprobado (Habilitado)'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado de Carnet')),
                ('motivo_rechazo', models.TextField(blank=True, null=True, verbose_name='Motivo de Rechazo')),
                ('tipo_sangre', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de Sangre')),
                ('contacto_emergencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto de Emergencia')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Emergencia')),
                ('firma_digital', models.BooleanField(default=False, verbose_name='Aceptación de Responsabilidad y Salud')),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='teams.equipo', verbose_name='Equipo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_jugador', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Jugador')),
            ],
            options={
                'verbose_name': 'Ficha de Jugador',
                'verbose_name_plural': 'Fichas de Jugadores',
            },
        ),
        migrations.CreateModel(
            name='InvitacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='teams.equipo')),
            ],
            options={
                'verbose_name': 'Invitación de Equipo',
                'verbose_name_plural': 'Invitaciones de Equipos',
            },
        ),
    ]
