# Generated by Django 6.0.5 on 2026-05-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='entrenador',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Entrenador / DT'),
        ),
    ]
