# Generated by Django 6.0.4 on 2026-05-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_equipo_entrenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='telefono_entrenador',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Entrenador'),
        ),
    ]
