# Generated by Django 6.0.4 on 2026-06-17 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_equipo_telefono_entrenador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fichajugador',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado Por'),
        ),
        migrations.AddField(
            model_name='fichajugador',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación'),
        ),
        migrations.AddField(
            model_name='fichajugador',
            name='nro_cedula',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Cédula'),
        ),
        migrations.AddField(
            model_name='fichajugador',
            name='numero_camiseta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Camiseta'),
        ),
    ]
