# Generated by Django 6.0.4 on 2026-06-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_fichajugador_aprobado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichajugador',
            name='firma_imagen',
            field=models.TextField(blank=True, null=True, verbose_name='Firma Dibujada (Base64)'),
        ),
    ]
