# Generated by Django 6.0.4 on 2026-06-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_fichajugador_firma_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='alineacion',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Alineación Táctica'),
        ),
    ]
