# Generated by Django 6.0.4 on 2026-06-17 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_equipo_alineacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invitacionequipo',
            name='tipo',
            field=models.CharField(choices=[('jugador', 'Jugador'), ('dt', 'Director Técnico / Staff')], default='jugador', max_length=20, verbose_name='Tipo de Invitado'),
        ),
        migrations.CreateModel(
            name='FichaDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='dt/selfies/', verbose_name='Foto / Selfie Carnet')),
                ('cedula_frontal', models.ImageField(blank=True, null=True, upload_to='dt/cedulas/', verbose_name='Cédula Frontal')),
                ('cedula_posterior', models.ImageField(blank=True, null=True, upload_to='dt/cedulas/', verbose_name='Cédula Posterior')),
                ('nro_cedula', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Cédula')),
                ('estado_validacion', models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('aprobado', 'Aprobado (Habilitado)'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado de Carnet')),
                ('motivo_rechazo', models.TextField(blank=True, null=True, verbose_name='Motivo de Rechazo')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('tipo_sangre', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo de Sangre')),
                ('contacto_emergencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contacto de Emergencia')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Emergencia')),
                ('firma_digital', models.BooleanField(default=False, verbose_name='Aceptación de Responsabilidad y Salud')),
                ('firma_imagen', models.TextField(blank=True, null=True, verbose_name='Firma Dibujada (Base64)')),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dts_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado Por')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuerpo_tecnico', to='teams.equipo', verbose_name='Equipo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_dt', to=settings.AUTH_USER_MODEL, verbose_name='Usuario DT')),
            ],
            options={
                'verbose_name': 'Ficha de Director Técnico',
                'verbose_name_plural': 'Fichas de Directores Técnicos',
            },
        ),
    ]
