# Generated by Django 4.2.30 on 2026-08-13 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0008_alter_equipo_categoria_alter_equipo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichadt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_dt', to=settings.AUTH_USER_MODEL, verbose_name='Usuario DT'),
        ),
        migrations.AlterField(
            model_name='fichajugador',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_jugador', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Jugador'),
        ),
    ]
