# Generated by Django 4.2.30 on 2026-08-13 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_torneo_max_jugadores_por_equipo_torneo_modalidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0009_alter_fichadt_user_alter_fichajugador_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichadt',
            name='torneo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichas_dts', to='matches.torneo', verbose_name='Torneo / Liga'),
        ),
        migrations.AddField(
            model_name='fichajugador',
            name='torneo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichas_jugadores', to='matches.torneo', verbose_name='Torneo / Liga'),
        ),
        migrations.AddField(
            model_name='invitacionequipo',
            name='torneo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='matches.torneo'),
        ),
        migrations.AlterUniqueTogether(
            name='fichadt',
            unique_together={('user', 'torneo')},
        ),
        migrations.AlterUniqueTogether(
            name='fichajugador',
            unique_together={('user', 'torneo')},
        ),
    ]
