# Generated by Django 4.2.30 on 2026-08-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_fichadt_torneo_fichajugador_torneo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='max_jugadores',
            field=models.IntegerField(default=25, verbose_name='Máximo de Jugadores'),
        ),
    ]
