# Generated by Django 4.2.30 on 2026-08-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_equipo_max_jugadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichajugador',
            name='partidos_suspension',
            field=models.IntegerField(default=0, verbose_name='Partidos de Suspensión Pendientes'),
        ),
    ]
