# Generated by Django 4.2.30 on 2026-08-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_fichajugador_partidos_suspension'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichajugador',
            name='es_lesionado',
            field=models.BooleanField(default=False, verbose_name='¿Está Lesionado?'),
        ),
    ]
