# Generated by Django 4.2.30 on 2026-08-17 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_migrate_categories_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='categoria',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='categoria_fk',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterUniqueTogether(
            name='equipo',
            unique_together={('nombre', 'categoria')},
        ),
    ]
