# Generated by Django 4.2.30 on 2026-09-03 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0012_partido_organizacion_torneo_organizacion'),
        ('users', '0008_organizacion_usuarioorganizacion'),
        ('teams', '0016_remove_equipo_categoria_fk_alter_equipo_categoria'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='equipo',
        #     unique_together=set(),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='fichadt',
        #     unique_together=set(),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='fichajugador',
        #     unique_together=set(),
        # ),
        migrations.AddField(
            model_name='categoria',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='fichadt',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='fichajugador',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='invitacionequipo',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='equipo',
                    unique_together={('organizacion', 'nombre', 'categoria')},
                ),
                migrations.AlterUniqueTogether(
                    name='fichadt',
                    unique_together={('organizacion', 'user', 'torneo')},
                ),
                migrations.AlterUniqueTogether(
                    name='fichajugador',
                    unique_together={('organizacion', 'user', 'torneo')},
                ),
            ],
            database_operations=[]
        ),
    ]
