# Generated by Django 4.2.30 on 2026-09-03 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_data_migration_org'),
        ('teams', '0017_alter_equipo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='organizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipo',
            name='organizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichadt',
            name='organizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichajugador',
            name='organizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitacionequipo',
            name='organizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización'),
            preserve_default=False,
        ),
    ]
