# Generated by Django 4.2.30 on 2026-09-08 17:14

from django.db import migrations, models
import django.db.models.deletion


def copy_existing_categorias(apps, schema_editor):
    Equipo = apps.get_model('teams', 'Equipo')
    for equipo in Equipo.objects.all():
        if equipo.categoria:
            equipo.categorias.add(equipo.categoria)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_role_alter_usuarioorganizacion_rol'),
        ('teams', '0018_alter_categoria_organizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='equipos', to='teams.categoria', verbose_name='Categorías en las que participa'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.categoria', verbose_name='Categoría Principal (Opcional)'),
        ),
        migrations.RunPython(copy_existing_categorias, reverse_code=migrations.RunPython.noop),
    ]
