# Generated by Django 6.0.4 on 2026-06-16 18:14

from django.db import migrations


def make_superusers_superadmins(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.filter(is_superuser=True).update(role='superadmin')

def rollback(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_telefono'),
    ]

    operations = [
        migrations.RunPython(make_superusers_superadmins, rollback),
    ]
