# Generated by Django 6.0.4 on 2026-06-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20260616_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('module', models.CharField(max_length=50)),
                ('allowed', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('role', 'module')},
            },
        ),
    ]
