# Generated by Django 6.0.4 on 2026-06-16 20:17

from django.db import migrations


def capitalize_existing_data(apps, schema_editor):
    try:
        CustomUser = apps.get_model('users', 'CustomUser')
        for u in CustomUser.objects.all():
            if u.first_name:
                u.first_name = u.first_name.upper()
            if u.last_name:
                u.last_name = u.last_name.upper()
            u.save()
    except Exception:
        pass

    try:
        Equipo = apps.get_model('teams', 'Equipo')
        for e in Equipo.objects.all():
            if e.nombre:
                e.nombre = e.nombre.upper()
            if e.entrenador:
                e.entrenador = e.entrenador.upper()
            e.save()
    except Exception:
        pass

    try:
        FichaJugador = apps.get_model('teams', 'FichaJugador')
        for f in FichaJugador.objects.all():
            if f.tipo_sangre:
                f.tipo_sangre = f.tipo_sangre.upper()
            if f.contacto_emergencia:
                f.contacto_emergencia = f.contacto_emergencia.upper()
            if f.motivo_rechazo:
                f.motivo_rechazo = f.motivo_rechazo.upper()
            f.save()
    except Exception:
        pass

    try:
        Torneo = apps.get_model('matches', 'Torneo')
        for t in Torneo.objects.all():
            if t.nombre:
                t.nombre = t.nombre.upper()
            if t.temporada:
                t.temporada = t.temporada.upper()
            t.save()
    except Exception:
        pass

    try:
        Partido = apps.get_model('matches', 'Partido')
        for p in Partido.objects.all():
            if p.estadio:
                p.estadio = p.estadio.upper()
            if p.temporada:
                p.temporada = p.temporada.upper()
            p.save()
    except Exception:
        pass

def rollback(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rolepermission'),
    ]

    operations = [
        migrations.RunPython(capitalize_existing_data, rollback),
    ]
