# Generated by Django 6.0.4 on 2026-06-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20260616_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin / Organizador'), ('dirigente', 'Dirigente / Representante'), ('jugador', 'Jugador'), ('dt', 'Director Técnico / Staff'), ('arbitro', 'Árbitro'), ('espectador', 'Espectador'), ('tesoreria', 'Tesorería'), ('comision', 'Comisión Técnica'), ('vocal', 'Vocal de Campo')], default='espectador', max_length=20),
        ),
    ]
