# Generated by Django 4.2.30 on 2026-09-03 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_id_alter_rolepermission_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de Organización')),
                ('nombre_comercial', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Comercial')),
                ('razon_social', models.CharField(blank=True, max_length=150, null=True, verbose_name='Razón Social')),
                ('ruc', models.CharField(blank=True, max_length=50, null=True, verbose_name='RUC / NIT')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizaciones/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='organizaciones/favicons/')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(default='Nicaragua', max_length=100)),
                ('moneda', models.CharField(default='NIO', max_length=10)),
                ('zona_horaria', models.CharField(default='America/Managua', max_length=50)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('suspendida', 'Suspendida'), ('inactiva', 'Inactiva')], default='activa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_activacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
            },
        ),
        migrations.CreateModel(
            name='UsuarioOrganizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('superadmin', 'Super Admin / Organizador'), ('dirigente', 'Dirigente / Representante'), ('jugador', 'Jugador'), ('dt', 'Director Técnico / Staff'), ('arbitro', 'Árbitro'), ('espectador', 'Espectador'), ('tesoreria', 'Tesorería'), ('comision', 'Comisión Técnica'), ('vocal', 'Vocal de Campo')], default='espectador', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='users.organizacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario por Organización',
                'verbose_name_plural': 'Usuarios por Organización',
                'unique_together': {('usuario', 'organizacion')},
            },
        ),
    ]
