# Generated by Django 4.2.30 on 2026-09-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_organizacion_usuarioorganizacion'),
        ('teams', '0017_alter_equipo_unique_together_and_more'),
        ('matches', '0012_partido_organizacion_torneo_organizacion'),
        ('finances', '0004_cobroequipo_organizacion_movimientocaja_organizacion_and_more'),
    ]

    def create_default_org(apps, schema_editor):
        Organizacion = apps.get_model('users', 'Organizacion')
        UsuarioOrganizacion = apps.get_model('users', 'UsuarioOrganizacion')
        CustomUser = apps.get_model('users', 'CustomUser')
        
        # Models to update
        Categoria = apps.get_model('teams', 'Categoria')
        Equipo = apps.get_model('teams', 'Equipo')
        FichaJugador = apps.get_model('teams', 'FichaJugador')
        FichaDT = apps.get_model('teams', 'FichaDT')
        InvitacionEquipo = apps.get_model('teams', 'InvitacionEquipo')
        
        Torneo = apps.get_model('matches', 'Torneo')
        Partido = apps.get_model('matches', 'Partido')
        
        PagoInscripcion = apps.get_model('finances', 'PagoInscripcion')
        MultaTarjeta = apps.get_model('finances', 'MultaTarjeta')
        MovimientoCaja = apps.get_model('finances', 'MovimientoCaja')
        CobroEquipo = apps.get_model('finances', 'CobroEquipo')

        # Create default organization
        org, created = Organizacion.objects.get_or_create(
            codigo='FUTBOL-PRO',
            defaults={
                'nombre': 'Fútbol Pro Original',
                'estado': 'activa'
            }
        )

        # Assign to all users
        for user in CustomUser.objects.all():
            UsuarioOrganizacion.objects.get_or_create(
                usuario=user,
                organizacion=org,
                defaults={'rol': user.role, 'activo': True}
            )

        # Update Teams
        Categoria.objects.update(organizacion=org)
        Equipo.objects.update(organizacion=org)
        FichaJugador.objects.update(organizacion=org)
        FichaDT.objects.update(organizacion=org)
        InvitacionEquipo.objects.update(organizacion=org)

        # Update Matches
        Torneo.objects.update(organizacion=org)
        Partido.objects.update(organizacion=org)

        # Update Finances
        PagoInscripcion.objects.update(organizacion=org)
        MultaTarjeta.objects.update(organizacion=org)
        MovimientoCaja.objects.update(organizacion=org)
        CobroEquipo.objects.update(organizacion=org)


    operations = [
        migrations.RunPython(create_default_org, reverse_code=migrations.RunPython.noop),
    ]
