# Generated by Django 4.2.30 on 2026-09-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_data_migration_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Administrador de Organización'), ('dirigente', 'Dirigente / Representante'), ('jugador', 'Jugador'), ('dt', 'Director Técnico / Staff'), ('arbitro', 'Árbitro'), ('espectador', 'Espectador'), ('tesoreria', 'Tesorería'), ('comision', 'Comisión Técnica'), ('vocal', 'Vocal de Campo')], default='espectador', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarioorganizacion',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Administrador de Organización'), ('dirigente', 'Dirigente / Representante'), ('jugador', 'Jugador'), ('dt', 'Director Técnico / Staff'), ('arbitro', 'Árbitro'), ('espectador', 'Espectador'), ('tesoreria', 'Tesorería'), ('comision', 'Comisión Técnica'), ('vocal', 'Vocal de Campo')], default='espectador', max_length=20),
        ),
    ]
