# Generated by Django 6.0.5 on 2026-05-18 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso (+)'), ('egreso', 'Egreso (-)')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (C$)')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto/Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
            },
        ),
        migrations.CreateModel(
            name='MultaTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de Multa (C$)')),
                ('motivo', models.CharField(choices=[('amarilla', 'Tarjeta Amarilla (C$ 50.00)'), ('roja', 'Tarjeta Roja (C$ 150.00)')], max_length=20, verbose_name='Motivo Sanción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado', 'Pagado')], default='pendiente', max_length=20, verbose_name='Estado de Pago')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago de Multa')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='teams.equipo', verbose_name='Equipo Sancionado')),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multa_tarjeta', to='matches.eventopartido', verbose_name='Incidencia de Tarjeta')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to=settings.AUTH_USER_MODEL, verbose_name='Jugador Sancionado')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='matches.partido', verbose_name='Partido')),
            ],
            options={
                'verbose_name': 'Multa por Tarjeta',
                'verbose_name_plural': 'Multas por Tarjetas',
            },
        ),
        migrations.CreateModel(
            name='PagoInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10, verbose_name='Monto (C$)')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=20, verbose_name='Estado de Pago')),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('billetera_movil', 'Billetera Móvil')], max_length=50, null=True, verbose_name='Método de Pago')),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante / Recibo')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas/Observaciones')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_inscripcion', to='teams.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Pago de Inscripción',
                'verbose_name_plural': 'Pagos de Inscripciones',
            },
        ),
    ]
