# Generated by Django 4.2.30 on 2026-08-13 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_fichajugador_partidos_suspension'),
        ('finances', '0002_alter_movimientocaja_id_alter_multatarjeta_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocaja',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto ($)'),
        ),
        migrations.AlterField(
            model_name='multatarjeta',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de Multa ($)'),
        ),
        migrations.AlterField(
            model_name='multatarjeta',
            name='motivo',
            field=models.CharField(choices=[('amarilla', 'Tarjeta Amarilla ($ 50.00)'), ('roja', 'Tarjeta Roja ($ 150.00)')], max_length=20, verbose_name='Motivo Sanción'),
        ),
        migrations.AlterField(
            model_name='pagoinscripcion',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=10, verbose_name='Monto ($)'),
        ),
        migrations.CreateModel(
            name='CobroEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(choices=[('arbitraje', 'Cuota de Arbitraje'), ('inscripcion', 'Cuota de Inscripción'), ('multa', 'Multa / Sanción Disciplinaria'), ('otro', 'Otro Cobro')], max_length=50, verbose_name='Concepto')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción Detallada')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto ($)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado', 'Pagado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobros_adicionales', to='teams.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Cobro a Equipo',
                'verbose_name_plural': 'Cobros a Equipos',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
