# Generated by Django 4.2.30 on 2026-09-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_organizacion_usuarioorganizacion'),
        ('finances', '0003_alter_movimientocaja_monto_alter_multatarjeta_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobroequipo',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='multatarjeta',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización'),
        ),
        migrations.AddField(
            model_name='pagoinscripcion',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización'),
        ),
    ]
