# Generated by Django 4.2.30 on 2026-09-03 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_data_migration_org'),
        ('finances', '0004_cobroequipo_organizacion_movimientocaja_organizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobroequipo',
            name='organizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='organizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='multatarjeta',
            name='organizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagoinscripcion',
            name='organizacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización'),
            preserve_default=False,
        ),
    ]
