# Generated by Django 4.2.30 on 2026-09-03 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_data_migration_org'),
        ('finances', '0005_alter_cobroequipo_organizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaOrganizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=50, verbose_name='Tipo de Documento')),
                ('prefijo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Prefijo')),
                ('ultimo_numero', models.IntegerField(default=0, verbose_name='Último Número Usado')),
                ('longitud', models.IntegerField(default=6, verbose_name='Longitud del Número')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.organizacion', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Secuencia de Organización',
                'verbose_name_plural': 'Secuencias de Organizaciones',
                'unique_together': {('organizacion', 'tipo_documento')},
            },
        ),
    ]
