# Generated by Django 4.2.30 on 2026-09-28 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0022_estadio_partido_estadio_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0006_secuenciaorganizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multatarjeta',
            name='evento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multa_tarjeta', to='matches.eventopartido', verbose_name='Incidencia de Tarjeta'),
        ),
        migrations.AlterField(
            model_name='multatarjeta',
            name='jugador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multas', to=settings.AUTH_USER_MODEL, verbose_name='Jugador Sancionado'),
        ),
        migrations.AlterField(
            model_name='multatarjeta',
            name='motivo',
            field=models.CharField(choices=[('amarilla', 'Tarjeta Amarilla'), ('roja', 'Tarjeta Roja'), ('sancion', 'Sanción Disciplinaria / Administrativa')], max_length=20, verbose_name='Motivo Sanción'),
        ),
        migrations.AlterField(
            model_name='multatarjeta',
            name='partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multas', to='matches.partido', verbose_name='Partido'),
        ),
    ]
