# Generated by Django 4.2.30 on 2026-10-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_alter_multatarjeta_evento_alter_multatarjeta_jugador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multatarjeta',
            name='motivo',
            field=models.CharField(choices=[('amarilla', 'Tarjeta Amarilla'), ('roja', 'Tarjeta Roja'), ('arbitraje', 'Cuota de Arbitraje / Vocalía'), ('sancion', 'Sanción Disciplinaria / Administrativa')], max_length=20, verbose_name='Motivo Sanción'),
        ),
    ]
